# Generated by Django 3.1.2 on 2020-10-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mypost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPost',
        ),
    ]
